[package]
name = "note-cli"
version = "0.1.9"
edition = "2024"
license = "MIT"
authors = ["Taiga Ito Boyintyoko@gmail.com"]
description = "Simple memo CLI with fzf support"
repository = "https://github.com/boyintyoko/note"


[dependencies]

[[bin]]
name = "note"
path = "src/main.rs"
